import { expect, test } from "@playwright/test";
import { access } from "node:fs/promises";
import path from "node:path";
import { createProject, fixturePath, importMarkdown, readDraftBody, registerAccount, setDraftBody, tutorialProjectId } from "./app";

test("shared helpers register, create, persist both editors and import an absolute fixture", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const credentials = await registerAccount(page, { prefix: "batch0smoke" });
  expect(credentials.account).toBeTruthy();
  expect(credentials.password.length).toBeGreaterThanOrEqual(10);
  const tutorialId = await tutorialProjectId(page);
  const id = await createProject(page, "共享辅助函数冒烟作品", { kind: "奇幻", summary: "验证隔离浏览器环境。" });
  expect(id).not.toBe(tutorialId);
  await page.getByRole("button", { name: "写作与检查", exact: true }).click();
  const body = "第一段：清晨的潮汐门。\n\n第二段：银钥匙由守塔人保管。\n";
  await setDraftBody(page, body);
  const saved = page.waitForResponse((response) => response.request().method() === "PATCH" && /\/drafts\/[^/?]+$/.test(new URL(response.url()).pathname));
  await page.getByRole("button", { name: "保存草稿", exact: true }).click();
  expect((await saved).ok()).toBe(true);
  await expect(page.locator(".workspace-save-summary")).toContainText("已保存");
  await page.reload();
  await expect.poll(() => readDraftBody(page)).toBe(body);
  await page.getByRole("button", { name: "进入沉浸写作", exact: true }).click();
  await expect.poll(() => readDraftBody(page, { immersive: true })).toBe(body);
  const immersiveBody = "沉浸第一段。\n沉浸第二段。";
  await setDraftBody(page, immersiveBody, { immersive: true });
  const immersiveSaved = page.waitForResponse((response) => response.request().method() === "PATCH" && /\/drafts\/[^/?]+$/.test(new URL(response.url()).pathname));
  await page.getByRole("button", { name: "在沉浸模式中保存草稿", exact: true }).click();
  expect((await immersiveSaved).ok()).toBe(true);
  await expect(page.locator(".immersive-save-state")).toContainText("已保存");
  await page.getByRole("button", { name: "退出沉浸写作并返回写作与检查", exact: true }).click();
  await page.reload();
  await expect.poll(() => readDraftBody(page)).toBe(immersiveBody);
  const fixture = fixturePath("stage9-mist-harbor.md");
  expect(path.isAbsolute(fixture)).toBe(true);
  await access(fixture);
  const importedId = await importMarkdown(page, "stage9-mist-harbor.md", "共享辅助函数导入作品");
  expect(importedId).not.toBe(id);
  await expect(page.getByRole("heading", { name: "共享辅助函数导入作品", exact: true })).toBeVisible();
});
