import { test, expect } from "@playwright/test";
import { readFile, writeFile } from "node:fs/promises";

test("相同依据可复用作者判断，关闭后恢复待处理且保留来源", async ({ page }, testInfo) => {
  const account = `reuse${Date.now()}`;
  const post = (path: string, data: unknown) => page.request.post(path, { data, headers: { "Idempotency-Key": crypto.randomUUID() } });
  const registered = await post("/api/auth/register", { account_name: account, display_name: "复用验收作者", password: `safe-${crypto.randomUUID()}`, recovery_email: `${account}@example.test` });
  expect(registered.status()).toBe(201);
  const projectId = (await registered.json()).data.onboarding.tutorial.project_id;
  const base = `/api/projects/${projectId}`;
  const project = (await (await page.request.get(base)).json()).data;
  const check = async () => {
    const started = await post(`${base}/checks`, { draft_id: project.current_draft.id, draft_revision: project.current_draft.revision });
    expect(started.status()).toBe(202);
    const id = (await started.json()).data.run_id;
    await expect.poll(async () => (await (await page.request.get(`${base}/checks/${id}`)).json()).data.status).toBe("completed");
    return (await (await page.request.get(`${base}/checks/${id}?include=issues,evidence,metrics`)).json()).data;
  };
  const first = await check();
  const issue = first.issues.find((item: { available_actions?: string[]; evidence_status: string }) => item.available_actions?.includes("keep_intentional") || (!item.available_actions && item.evidence_status === "sufficient"));
  expect(issue).toBeTruthy();
  const decided = await post(`${base}/issues/${issue.id}/decision`, { run_id: first.run_id, source_revision: first.source_revision, decision: "keep_intentional", note: "作者核对后明确保留此处叙述；仅在相同依据下沿用。" });
  expect(decided.ok()).toBe(true);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`/projects/${projectId}/sources#long-term-review`);
  const maintenance = page.getByRole("region", { name: "修订历史章节与复核事实" });
  await maintenance.getByText("复用已作出的作者判断", { exact: false }).first().click();
  await maintenance.getByRole("button", { name: "启用判断复用", exact: true }).click();
  await expect(maintenance.getByText("判断复用已启用", { exact: true })).toBeVisible();
  const second = await check();
  const reused = second.issues.filter((item: { reused_decision?: unknown }) => item.reused_decision);
  expect(reused.length).toBeGreaterThan(0);
  expect(reused[0].evidence.length).toBeGreaterThan(0);
  await page.getByRole("button", { name: "写作与检查", exact: true }).click();
  await expect(page.getByText("沿用作者此前判断", { exact: false }).first()).toBeVisible();
  const undecidedCount = second.issues.filter((item: { status: string }) => item.status === "open").length;
  await expect(page.getByRole("heading", { name: /^待处理提示/ })).toHaveText(`待处理提示 ${undecidedCount}`);
  await page.screenshot({ path: testInfo.outputPath("reused-author-decision.png"), fullPage: true, animations: "disabled" });
  await page.goto(`/projects/${projectId}/sources#long-term-review`);
  await maintenance.getByText("复用已作出的作者判断", { exact: false }).first().click();
  await maintenance.getByRole("button", { name: "停止复用", exact: true }).click();
  await expect(maintenance.getByText("判断复用未启用", { exact: true })).toBeVisible();
  const disabled = (await (await page.request.get(`${base}/checks/${second.run_id}?include=issues,evidence,metrics`)).json()).data;
  expect(disabled.issues.every((item: { reused_decision?: unknown }) => !item.reused_decision)).toBe(true);
  expect(disabled.issues.find((item: {id: string}) => item.id === reused[0].id).status).toBe("open");
});

test("作者下载完整资料、修订历史章节、逐项复核并保留历史来源", async ({ page }, testInfo) => {
  const failures: string[] = [];
  page.on("pageerror", (error) => failures.push(error.message));
  const request = page.request;
  const account = `maintenance${Date.now()}`;
  const registered = await request.post("/api/auth/register", { data: { account_name: account, display_name: "维护验收作者", password: `safe-${crypto.randomUUID()}`, recovery_email: `${account}@example.test` }, headers: { "Idempotency-Key": crypto.randomUUID() } });
  expect(registered.status()).toBe(201);
  const post = async (path: string, data: unknown) => {
    const response = await request.post(path, { data, headers: { "Idempotency-Key": crypto.randomUUID() } });
    expect(response.ok(), `${path}: ${await response.text()}`).toBe(true);
    return (await response.json()).data;
  };
  const source = "# 雾港初章\n\n钟声响起后，所有船只必须停泊在雾港。\n\n# 北堤钥匙\n\n林默一直保管银钥匙。\n\n# 清晨门扉\n\n林默知道北堤门只在清晨开启。";
  const importedPreview = await request.post("/api/imports/preview", { multipart: { file: { name: "maintenance.md", mimeType: "text/markdown", buffer: Buffer.from(source) } }, headers: { "Idempotency-Key": crypto.randomUUID() } });
  expect(importedPreview.ok()).toBe(true);
  const importPreview = (await importedPreview.json()).data;
  const imported = await post(`/api/imports/${importPreview.import_id}/commit`, { confirm: true, title: "维护验收作品", chapter_preview_ids: importPreview.detected.chapters.map((chapter: {preview_id: string}) => chapter.preview_id) });
  const projectId = imported.project.id;
  const initialized = await post(`/api/projects/${projectId}/memory/initializations`, { source_revision: 1 });
  for (const candidate of initialized.initialization.candidates) {
    await post(`/api/projects/${projectId}/memory/initializations/${initialized.initialization.id}/candidates/${candidate.id}/decision`, { decision: "accepted" });
  }
  await post(`/api/projects/${projectId}/memory/initializations/${initialized.initialization.id}/commit`, { confirm: true });
  const draft = (await (await request.get(`/api/projects/${projectId}`)).json()).data.current_draft;
  const savedDraft = await request.patch(`/api/projects/${projectId}/drafts/${draft.id}`, { data: { base_revision: draft.revision, body: "林默站在雾港的岸边，等待清晨。" }, headers: { "Idempotency-Key": crypto.randomUUID() } });
  expect(savedDraft.ok()).toBe(true);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`/projects/${projectId}/overview`);
  await expect(page.getByRole("heading", { name: "导出作品", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("overview.png"), fullPage: true, animations: "disabled" });
  const panel = page.getByRole("region", { name: "作品导出" });
  await panel.getByRole("checkbox").check();
  for (const format of ["txt", "markdown", "bundle"]) {
    await panel.getByRole("combobox").selectOption(format);
    const downloadWait = page.waitForEvent("download");
    await panel.getByRole("button", { name: /下载/ }).click();
    const download = await downloadWait;
    const target = testInfo.outputPath(download.suggestedFilename());
    await download.saveAs(target);
    const bytes = await readFile(target);
    expect(bytes.length).toBeGreaterThan(100);
    if (format === "bundle") expect(bytes.subarray(0, 2).toString()).toBe("PK");
    else expect(bytes.toString("utf8")).toContain("章");
  }
  await page.getByRole("button", { name: "修订历史章节与复核事实", exact: true }).click();
  const maintenance = page.getByRole("region", { name: "修订历史章节与复核事实" });
  await expect(maintenance).toBeVisible();
  await maintenance.getByText("已入库章节", { exact: false }).first().click();
  await maintenance.getByRole("button", { name: "修订本章" }).first().click();
  const title = maintenance.getByRole("textbox", { name: "修订章节标题", exact: true });
  // A nested textarea's initial text also appears in its label's textContent;
  // match the accessible textbox name so nonempty imported chapters are located.
  const body = maintenance.getByRole("textbox", { name: "修订章节正文", exact: true });
  const originalTitle = await title.inputValue();
  const originalBody = await body.inputValue();
  await title.fill(`${originalTitle}（修订）`);
  await body.fill(originalBody + "\n海风轻轻掠过墙边的灯笼。");
  await page.getByRole("button", { name: "项目概览", exact: true }).click();
  await expect(page.getByRole("heading", { name: "导出作品", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "修订历史章节与复核事实", exact: true }).click();
  await maintenance.getByRole("button", { name: "恢复本机修订", exact: true }).click();
  await expect(title).toHaveValue(`${originalTitle}（修订）`);
  await expect(body).toHaveValue(originalBody + "\n海风轻轻掠过墙边的灯笼。");
  await maintenance.getByRole("button", { name: "预览修订影响" }).click();
  await expect(maintenance.getByRole("heading", { name: "确认这次正文修订" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("chapter-preview.png"), fullPage: true, animations: "disabled" });
  await maintenance.getByRole("button", { name: "确认提交章节修订" }).click();
  await expect(maintenance.getByRole("status")).toContainText("章节修订已保存");
  let state = (await (await request.get(`/api/projects/${projectId}/long-term-review`)).json()).data;
  expect(state.source_revision).toBe(2);
  expect(state.chapters[0].body).toContain("海风轻轻");
  expect(state.source_revision_reviews.filter((r: {status: string}) => r.status === "pending").length).toBeGreaterThan(0);
  await expect(maintenance.getByRole("button", { name: "确认仍有依据，保留事实" }).first()).toBeDisabled();
  const project = (await (await request.get(`/api/projects/${projectId}`)).json()).data;
  const blocked = await request.post(`/api/projects/${projectId}/checks`, { data: { draft_id: project.current_draft.id, draft_revision: project.current_draft.revision }, headers: { "Idempotency-Key": crypto.randomUUID() } });
  expect(blocked.status()).toBe(409);
  expect((await blocked.json()).error.code).toBe("source_revision_review_required");
  while (await maintenance.getByRole("button", { name: "确认仍有依据，保留事实" }).count()) {
    await maintenance.getByLabel("复核说明（必填）").first().fill("已核对修订前后正文，只新增环境描写，原事实依据仍成立。");
    const button = maintenance.getByRole("button", { name: "确认仍有依据，保留事实" }).first();
    const count = await maintenance.getByRole("button", { name: "确认仍有依据，保留事实" }).count();
    await button.click();
    await expect(maintenance.getByRole("button", { name: "确认仍有依据，保留事实" })).toHaveCount(count - 1);
  }
  state = (await (await request.get(`/api/projects/${projectId}/long-term-review`)).json()).data;
  expect(state.source_revision_reviews.every((r: {status: string}) => r.status !== "pending")).toBeTruthy();
  const chapters = (await (await request.get(`/api/projects/${projectId}/chapters?include=excerpt`)).json()).data.chapters;
  expect(chapters[0].source_spans.some((s: {is_current?: boolean}) => s.is_current === false)).toBeTruthy();
  await page.reload();
  await expect(page.getByText("历史来源（已修订）", { exact: false }).first()).toBeVisible();
  await expect(page.getByText("修订正文", { exact: false }).first()).toBeVisible();
  await expect(page.getByText("chapter_revision", { exact: false })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("review-completed.png"), fullPage: true, animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload();
  await expect(maintenance.getByText("当前为阅读模式", { exact: false })).toBeVisible();
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
  await page.screenshot({ path: testInfo.outputPath("mobile-readonly.png"), fullPage: true, animations: "disabled" });
  expect(failures).toEqual([]);
  await writeFile(testInfo.outputPath("browser-evidence.json"), JSON.stringify({ projectId, sourceRevision: state.source_revision, memoryVersion: state.memory_version, downloads: 3, consoleErrors: failures, mobileOverflow: overflow }, null, 2));
});
