import { expect, test } from "@playwright/test";
import { randomUUID } from "node:crypto";

async function imported(page: import("@playwright/test").Page) {
  await page.goto("/register");
  await page.getByLabel("账号").fill(`stage11j${Date.now()}`);
  await page.getByLabel("显示名称").fill("11J 作者"); await page.getByLabel("密码").fill(`safe-${randomUUID()}`);
  const registered=page.waitForResponse((response)=>response.url().endsWith("/api/auth/register") && response.request().method()==="POST"); await page.getByRole("button", { name: "创建本地账号" }).click(); expect((await registered).status()).toBe(201);
  return importProject(page, "11J 浏览器作品");
}

async function importProject(page: import("@playwright/test").Page, title: string) {
  await page.getByRole("button", { name: "作品管理", exact: true }).click(); await page.getByRole("button", { name: "导入作品" }).click();
  await page.locator('input[name="file"]').setInputFiles({ name:"base.md", mimeType:"text/markdown", buffer:Buffer.from("# Base\n原始正文。") });
  await page.getByRole("button", { name:"解析并预览章节" }).click(); await page.getByRole("button", { name:"继续确认" }).click();
  await page.getByLabel("作品名").fill(title); const committed=page.waitForResponse((r)=>/\/api\/imports\/[^/]+\/commit$/.test(new URL(r.url()).pathname)); await page.getByRole("button", { name:"确认导入" }).click();
  return ((await (await committed).json()) as {data:{project:{id:string}}}).data.project.id;
}

test("paste preview and commit send real API rN to rN+1 and create next draft", async ({ page }) => {
  const id=await imported(page); await page.goto(`/projects/${id}/sources`);
  await page.getByLabel("章节正文").fill("# 新章\n新增正文。");
  const preview=page.waitForResponse((r)=>r.url().includes("source-change-sets/preview") && r.request().method()==="POST"); await page.getByRole("button", {name:"预览追加"}).click();
  expect((await preview).status()).toBe(201); await expect(page.getByRole("status").getByText("r1 → r2")).toBeVisible();
  const commit=page.waitForResponse((r)=>/source-change-sets\/.+\/commit/.test(r.url()) && r.request().method()==="POST"); await page.getByRole("button", {name:"确认追加并创建下一章草稿"}).click(); expect((await commit).status()).toBe(200);
  await expect(page.getByRole("status")).toContainText("已提交 source r2"); await expect(page.getByRole("status")).toContainText("下一章草稿：第 3 章"); await page.getByRole("button",{name:"进入下一章草稿"}).click(); await expect(page).toHaveURL(new RegExp(`/projects/${id}/workspace`));
  const project=await page.evaluate(async (projectId)=>await (await fetch(`/api/projects/${projectId}`)).json(),id); expect(project.data).toMatchObject({source_revision:2,current_draft:{chapter_number:3}});
  await page.goto(`/projects/${id}/overview`); await expect(page.getByText("Source r2",{exact:true})).toBeVisible();
});

test("390 is browse-only for every source append mutation after a desktop preview", async ({ page }) => {
  const id=await imported(page); await page.goto(`/projects/${id}/sources`); await page.locator('input[type="radio"]').nth(2).check();
  await page.locator('input[type="file"]').setInputFiles({name:"append.md",mimeType:"text/markdown",buffer:Buffer.from("# File\n正文")});
  const preview=page.waitForResponse((r)=>r.url().includes("source-change-sets/preview") && r.request().method()==="POST"); await page.getByRole("button",{name:"预览追加"}).click(); expect((await preview).status()).toBe(201);
  await page.setViewportSize({width:390,height:844});
  const radios=page.locator('input[type="radio"]'); await expect(radios).toHaveCount(3); for (let index=0; index<3; index+=1) await expect(radios.nth(index)).toBeDisabled(); await expect(page.locator('input[type="file"]')).toBeDisabled(); await expect(page.getByLabel("章节正文")).toBeDisabled();
  await expect(page.getByRole("button",{name:"预览追加"})).toBeDisabled(); await expect(page.getByRole("button",{name:"确认追加并创建下一章草稿"})).toBeDisabled();
});

test("file input previews and commits against its own project", async ({ page }) => { const id=await imported(page); await page.goto(`/projects/${id}/sources`); await page.locator('input[type="radio"]').nth(2).check(); await page.locator('input[type="file"]').setInputFiles({name:"append.md",mimeType:"text/markdown",buffer:Buffer.from("# File\n文件正文")}); const response=page.waitForResponse((r)=>r.url().includes("source-change-sets/preview")); await page.getByRole("button",{name:"预览追加"}).click(); expect((await response).status()).toBe(201); const payload=await (await response).json(); expect(payload.data.source_change_set).toMatchObject({project_id:id,base_source_revision:1,target_source_revision:2,input_method:"file"}); const commit=page.waitForResponse((r)=>/source-change-sets\/.+\/commit/.test(r.url()) && r.request().method()==="POST"); await page.getByRole("button",{name:"确认追加并创建下一章草稿"}).click(); expect((await commit).status()).toBe(200); });

test("draft complete saves then previews and commits its draft snapshot", async ({ page }) => { const id=await imported(page); await page.goto(`/projects/${id}/workspace`); await page.locator("#draft-body").fill("# Draft\n完成的章节正文"); await page.getByRole("button",{name:"保存草稿"}).click(); await page.goto(`/projects/${id}/sources`); await page.locator('input[type="radio"]').first().check(); const response=page.waitForResponse((r)=>r.url().includes("source-change-sets/preview")); await page.getByRole("button",{name:"预览追加"}).click(); expect((await response).status()).toBe(201); expect((await (await response).json()).data.source_change_set).toMatchObject({project_id:id,input_method:"draft_complete",base_source_revision:1,target_source_revision:2}); const commit=page.waitForResponse((r)=>/source-change-sets\/.+\/commit/.test(r.url()) && r.request().method()==="POST"); await page.getByRole("button",{name:"确认追加并创建下一章草稿"}).click(); expect((await commit).status()).toBe(200); });

test("stale commit fails closed, preserves paste input, and can recover with a new preview", async ({ page }) => { const id=await imported(page); await page.goto(`/projects/${id}/sources`); await page.getByLabel("章节正文").fill("# Recovery\n保留的内容"); const initial=page.waitForResponse((r)=>r.url().includes("source-change-sets/preview") && r.request().method()==="POST"); await page.getByRole("button",{name:"预览追加"}).click(); expect((await initial).status()).toBe(201); await page.evaluate(async (projectId)=>{ const headers={"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()}; const preview=await (await fetch(`/api/projects/${projectId}/source-change-sets/preview`,{method:"POST",headers,body:JSON.stringify({mode:"append",input_method:"paste",base_source_revision:1,content:"# Other\n正文"})})).json(); return fetch(`/api/projects/${projectId}/source-change-sets/${preview.data.source_change_set.id}/commit`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({confirm:true,content_sha256:preview.data.source_change_set.content_sha256})}); },id); const stale=page.waitForResponse((r)=>/source-change-sets\/.+\/commit/.test(r.url()) && r.request().method()==="POST"); await page.getByRole("button",{name:"确认追加并创建下一章草稿"}).click(); expect((await stale).status()).toBe(409); await expect(page.getByRole("alert").filter({hasText:"请保留当前内容"})).toContainText("请保留当前内容"); await expect(page.getByLabel("章节正文")).toHaveValue("# Recovery\n保留的内容"); const project=await page.evaluate(async (projectId)=>await (await fetch(`/api/projects/${projectId}`)).json(),id); expect(project.data).toMatchObject({source_revision:2,chapter_count:2}); await page.reload(); await expect(page.getByRole("heading",{name:"追加章节"})).toBeVisible(); });

test("a delayed project A preview cannot pollute project B", async ({ page }) => { const a=await imported(page); const b=await importProject(page,"11J 项目 B"); await page.goto("/projects"); const bRow=page.locator(".project-rows li").filter({hasText:"11J 项目 B"}); await bRow.getByRole("button",{name:"追加章节"}).click(); await expect(page).toHaveURL(new RegExp(`/projects/${b}/sources`)); type LatePayload={data:{source_change_set:{project_id:string;base_source_revision:number;target_source_revision:number}}}; let release!:()=>void; let intercepted!:()=>void; let fulfilled!:()=>void; let deliverPayload!:(payload:LatePayload)=>void; const releaseBarrier=new Promise<void>((resolve)=>{release=resolve}); const interceptedBarrier=new Promise<void>((resolve)=>{intercepted=resolve}); const fulfilledBarrier=new Promise<void>((resolve)=>{fulfilled=resolve}); const payloadBarrier=new Promise<LatePayload>((resolve)=>{deliverPayload=resolve}); await page.route(`**/api/projects/${a}/source-change-sets/preview`,async (route)=>{const response=await route.fetch(); deliverPayload(await response.json() as LatePayload); intercepted(); await releaseBarrier; await route.fulfill({response}); fulfilled();}); await page.goto(`/projects/${a}/sources`); await page.getByLabel("章节正文").fill("# A\nA"); await page.getByRole("button",{name:"预览追加"}).click(); await interceptedBarrier; await page.goto(`/projects/${b}/sources`); await expect(page.getByText("目标作品：11J 项目 B",{exact:false})).toBeVisible(); release(); await fulfilledBarrier; expect((await payloadBarrier).data.source_change_set).toMatchObject({project_id:a,base_source_revision:1,target_source_revision:2}); await expect(page).toHaveURL(new RegExp(`/projects/${b}/sources`)); await expect(page.getByText("SourceChangeSet 预览",{exact:false})).toHaveCount(0); const project=await page.evaluate(async (id)=>await (await fetch(`/api/projects/${id}`)).json(),b); expect(project.data.source_revision).toBe(1); });
