import { expect, test, type APIResponse, type Page } from "@playwright/test";
import { randomUUID } from "node:crypto";
import path from "node:path";

const backendOrigin=process.env.E2E_BACKEND_ORIGIN;
if(!backendOrigin)throw new Error("E2E_BACKEND_ORIGIN is required");
const accountPrefix=process.env.E2E_ACCOUNT_PREFIX;
if(!accountPrefix)throw new Error("E2E_ACCOUNT_PREFIX is required");
type Envelope<T>={data:T};
async function data<T>(response:APIResponse){expect(response.ok(),await response.text()).toBe(true);return ((await response.json()) as Envelope<T>).data;}
async function register(page:Page){
  const account=`${accountPrefix}bounded${Date.now()}${Math.floor(Math.random()*1000)}`.toLowerCase();
  await page.goto("/register");await page.getByLabel("账号").fill(account);await page.getByLabel("显示名称").fill("有界工具验收作者");await page.getByLabel("恢复邮箱").fill(`${account}@example.test`);await page.locator('input[name="password"]').fill(`safe-${randomUUID()}`);await page.getByRole("button",{name:"创建账号",exact:true}).click();
  await expect(page.getByRole("heading",{name:"继续你的故事",exact:true})).toBeVisible();
}
async function snap(page:Page,name:string){if(process.env.E2E_OUTPUT_DIR)await page.screenshot({path:path.join(process.env.E2E_OUTPUT_DIR,name),fullPage:true});}

test("v1.3.0 bounded Q&A and foreshadows keep author records primary, evidence real, and mobile read-only",async({page})=>{
  const consoleErrors:string[]=[],pageErrors:string[]=[],requestErrors:string[]=[];
  let expectedConflictCount=0;
  page.on("console",message=>{if(message.type()==="error")consoleErrors.push(message.text());});
  page.on("pageerror",error=>pageErrors.push(error.message));
  page.on("requestfailed",request=>requestErrors.push(`${request.method()} ${request.url()} ${request.failure()?.errorText??""}`));
  await page.setViewportSize({width:1440,height:960});
  const statsBefore=await (await page.request.get(`${backendOrigin}/api/test/stage12/stats`)).json() as {provider_http_calls:number};
  await register(page);
  const onboarding=await data<{tutorial:{project_id:string}}>(await page.request.get(`${backendOrigin}/api/onboarding`));
  const projectId=onboarding.tutorial.project_id;
  const project=await data<{source_revision:number;current_memory_version:number;author_context_version:number;foreshadow_version:number;current_draft:{id:string;revision:number}}>(await page.request.get(`${backendOrigin}/api/projects/${projectId}`));
  await page.goto(`/projects/${projectId}/workspace`);
  const tools=page.getByRole("region",{name:"有界问答与伏笔管理"});
  await expect(tools).toBeVisible();
  const editorBox=await page.locator(".workspace-grid").boundingBox(),toolBox=await tools.boundingBox();
  expect(editorBox&&toolBox&&editorBox.y<toolBox.y).toBe(true);
  await expect(tools.getByText(/作者伏笔 V0/)).toBeVisible();
  await tools.locator(":scope > summary").click();

  const recordTool=page.getByRole("region",{name:"伏笔管理"});
  const recordForm=recordTool.locator(".foreshadow-form");
  await recordForm.getByLabel("标题").fill("失落的潮汐表");
  await recordForm.getByLabel("说明").fill("作者计划在后续章节解释它的缺口。");
  await recordForm.locator("select").first().selectOption("planted");
  await recordForm.getByLabel("埋设章节 / 来源").selectOption({index:2});
  await recordForm.getByRole("button",{name:"新建作者记录",exact:true}).click();
  const authorRecord=recordTool.locator(".foreshadow-records article").filter({hasText:"失落的潮汐表"});
  await expect(authorRecord).toContainText("作者记录 · V1");
  await authorRecord.getByRole("button",{name:"编辑",exact:true}).click();
  await recordForm.getByLabel("标题").fill("潮汐表的旧缺口");
  await recordForm.getByLabel("说明").fill("作者确认该缺口仍在发展，并将于后续回收。");
  await recordForm.locator("select").first().selectOption("developing");
  await recordForm.getByRole("button",{name:"保存修改",exact:true}).click();
  await expect(recordTool.locator(".foreshadow-records article").filter({hasText:"潮汐表的旧缺口"})).toContainText("作者记录 · V2");

  const editingRecord=recordTool.locator(".foreshadow-records article").filter({hasText:"潮汐表的旧缺口"});
  await editingRecord.getByRole("button",{name:"编辑",exact:true}).click();
  await recordForm.getByLabel("标题").fill("潮汐表的本地修订");
  await recordForm.getByLabel("说明").fill("这是编辑窗口中尚未提交、不能被后台刷新静默覆盖的内容。");
  const recordsBeforeConflict=await data<{records:{id:string;title:string;version:number}[]}>(await page.request.get(`${backendOrigin}/api/projects/${projectId}/foreshadows?include_archived=true`));
  const serverRecord=recordsBeforeConflict.records.find(item=>item.title==="潮汐表的旧缺口");
  expect(serverRecord).toBeTruthy();
  const externalPatch=await page.request.patch(`${backendOrigin}/api/projects/${projectId}/foreshadows/${serverRecord!.id}`,{headers:{"Idempotency-Key":randomUUID()},data:{base_version:serverRecord!.version,description:"另一个窗口已先更新服务器记录。"}});
  expect(externalPatch.status()).toBe(200);

  const draftBody=page.locator("#draft-body");
  await draftBody.fill(`${await draftBody.inputValue()} 未保存内容不得进入分析。`);
  await expect(tools.getByText(/当前草稿有未保存修改/)).toBeVisible();
  await page.getByRole("region",{name:"有界问答"}).getByLabel("你的问题").fill("未保存稿是否被分析？");
  await expect(page.getByRole("region",{name:"有界问答"}).getByRole("button",{name:"提交问题",exact:true})).toBeDisabled();
  await expect(recordTool.getByRole("button",{name:"扫描已写正文",exact:true})).toBeDisabled();
  const noDirtyRuns=await data<{runs:unknown[]}>(await page.request.get(`${backendOrigin}/api/projects/${projectId}/analyses?analysis_type=story_qa&limit=20`));
  expect(noDirtyRuns.runs).toHaveLength(0);
  const dirtyDraftValue=await draftBody.inputValue();
  await editingRecord.locator(".foreshadow-links a").first().click();
  const unsavedDialog=page.getByRole("dialog",{name:"未保存草稿"});
  await expect(unsavedDialog).toBeVisible();
  await unsavedDialog.getByRole("button",{name:"取消",exact:true}).click();
  await expect(page).toHaveURL(new RegExp(`/projects/${projectId}/workspace$`));
  await expect(draftBody).toHaveValue(dirtyDraftValue);
  await page.getByRole("button",{name:"保存草稿",exact:true}).click();
  await expect(page.getByText("✓ 已保存",{exact:true})).toBeVisible();
  await expect(tools.getByText(/作者伏笔 V3/)).toBeVisible();
  await expect(recordForm.getByLabel("标题")).toHaveValue("潮汐表的本地修订");
  const expectedConflict=page.waitForResponse(response=>response.request().method()==="PATCH"&&new URL(response.url()).pathname===`/api/projects/${projectId}/foreshadows/${serverRecord!.id}`&&response.status()===409);
  await recordForm.getByRole("button",{name:"保存修改",exact:true}).click();
  const conflictResponse=await expectedConflict;
  expect(conflictResponse.status()).toBe(409);expectedConflictCount+=1;
  await expect(tools.getByRole("alert")).toContainText("你的标题、说明与引用选择仍保留");
  await expect.poll(()=>consoleErrors.filter(message=>message.includes("409 (Conflict)")).length).toBe(1);
  expect(consoleErrors.every(message=>message.includes("409 (Conflict)"))).toBe(true);
  consoleErrors.length=0;
  await expect(recordForm.getByLabel("说明")).toHaveValue("这是编辑窗口中尚未提交、不能被后台刷新静默覆盖的内容。");
  await tools.getByRole("button",{name:"载入最新版本",exact:true}).click();
  await expect(tools.getByText(/已载入最新伏笔版本/)).toBeVisible();
  await expect(recordForm.getByLabel("标题")).toHaveValue("潮汐表的本地修订");
  await recordForm.getByRole("button",{name:"保存修改",exact:true}).click();
  await expect(recordTool.locator(".foreshadow-records article").filter({hasText:"潮汐表的本地修订"})).toContainText("作者记录 · V4");

  const qa=page.getByRole("region",{name:"有界问答"});
  await qa.getByLabel("你的问题").fill("林默目前知道什么？");
  await qa.getByRole("button",{name:"提交问题",exact:true}).click();
  await expect(qa.getByText("根据当前 Story Memory，这个问题已有可核对的答案。",{exact:true})).toBeVisible();
  const qaRun=qa.locator(".bounded-run").first();
  const savedProject=await data<{current_draft:{revision:number}}>(await page.request.get(`${backendOrigin}/api/projects/${projectId}`));
  await expect(qaRun).toContainText(`草稿 r${savedProject.current_draft.revision}`);
  await expect(qaRun).toContainText(`来源 r${project.source_revision}`);
  await expect(qaRun).toContainText(`Story Memory V${project.current_memory_version}`);
  await expect(qaRun).toContainText(`Author Context V${project.author_context_version}`);
  await expect(qaRun).toContainText("作者伏笔 V4");
  await expect(qaRun).toContainText("检索 writing-analysis-lexical-v1");
  await draftBody.fill(`${await draftBody.inputValue()} 保存后旧问答必须立即过期。`);
  await expect(qa.getByRole("button",{name:"提交问题",exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"保存草稿",exact:true}).click();
  await expect(qaRun.getByText("依据已变化",{exact:true})).toBeVisible();
  const qaEvidence=qaRun.locator(".bounded-source-links a").first();
  const qaHref=await qaEvidence.getAttribute("href");
  expect(qaHref).toMatch(new RegExp(`/projects/${projectId}/memory#memory-`));
  const qaTarget=new URL(qaHref!,page.url()).hash.slice(1);
  await qaEvidence.click();
  await expect(page).toHaveURL(new RegExp(`/projects/${projectId}/memory#memory-`));
  const memoryAnchor=page.locator(`[id="${qaTarget}"]`);await expect(memoryAnchor).toBeVisible();
  expect(await memoryAnchor.evaluate(node=>{const box=node.getBoundingClientRect();return box.top<window.innerHeight&&box.bottom>0;})).toBe(true);

  await page.goto(`/projects/${projectId}/workspace`);await expect(tools).toBeVisible();await tools.locator(":scope > summary").click();
  const scanButton=recordTool.getByRole("button",{name:"扫描已写正文",exact:true});
  await scanButton.click();
  await expect(recordTool.getByText("发现两条需要作者逐条判断的伏笔候选。",{exact:true})).toBeVisible();
  await expect(recordTool.locator(".foreshadow-records article")).toHaveCount(1);
  const firstCandidate=recordTool.locator(".foreshadow-candidate").filter({hasText:"潮汐表的缺口"});
  const candidateEvidence=firstCandidate.locator(".bounded-source-links a").first();
  const candidateHref=await candidateEvidence.getAttribute("href");
  expect(candidateHref).toMatch(new RegExp(`/projects/${projectId}/sources#span-`));
  const candidateTarget=new URL(candidateHref!,page.url()).hash.slice(1);
  await candidateEvidence.click();
  await expect(page).toHaveURL(new RegExp(`/projects/${projectId}/sources#span-`));
  const sourceAnchor=page.locator(`[id="${candidateTarget}"]`);await expect(sourceAnchor).toBeVisible();
  expect(await sourceAnchor.evaluate(node=>{const box=node.getBoundingClientRect();return box.top<window.innerHeight&&box.bottom>0;})).toBe(true);

  await page.goto(`/projects/${projectId}/workspace`);await expect(tools).toBeVisible();await tools.locator(":scope > summary").click();
  const refreshedFirst=recordTool.locator(".foreshadow-candidate").filter({hasText:"潮汐表的缺口"});
  await refreshedFirst.getByText("编辑后接受",{exact:true}).click();
  await refreshedFirst.getByLabel("标题").fill("作者确认的潮汐表线索");
  await refreshedFirst.getByLabel("说明").fill("作者编辑后确认，后续需要安排明确回收。");
  await refreshedFirst.getByRole("button",{name:"保存为作者记录",exact:true}).click();
  await expect(recordTool.locator(".foreshadow-records article").filter({hasText:"作者确认的潮汐表线索"})).toContainText("作者记录");
  const secondCandidate=recordTool.locator(".foreshadow-candidate").filter({hasText:"北门雾钟"});
  await secondCandidate.getByRole("button",{name:"拒绝",exact:true}).click();
  await expect(secondCandidate).toContainText("作者已拒绝");
  await expect(recordTool.locator(".foreshadow-records article")).toHaveCount(2);

  await qa.getByLabel("你的问题").fill("E2E_QA_FAIL_ONCE 这条线索成立吗？");
  await qa.getByRole("button",{name:"提交问题",exact:true}).click();
  const failedQa=qa.locator(".bounded-run").filter({hasText:"E2E_QA_FAIL_ONCE"}).first();
  await expect(failedQa.getByText(/结果未通过结构校验/)).toBeVisible();
  await failedQa.getByRole("button",{name:"重试",exact:true}).click();
  await expect(qa.getByText("根据当前 Story Memory，这个问题已有可核对的答案。",{exact:true})).toHaveCount(2);

  await draftBody.fill(`${await draftBody.inputValue()} E2E_FORESHADOW_BLOCK`);
  await page.getByRole("button",{name:"保存草稿",exact:true}).click();
  await expect(page.getByText("✓ 已保存",{exact:true})).toBeVisible();
  await page.request.get(`${backendOrigin}/api/test/stage12/reset`);
  await scanButton.click();
  await expect.poll(async()=>((await (await page.request.get(`${backendOrigin}/api/test/stage12/stats`)).json()) as {blocked:boolean}).blocked).toBe(true);
  const activeScan=recordTool.locator(".foreshadow-scan").first();
  const cancelResponse=page.waitForResponse(response=>response.request().method()==="POST"&&/\/analyses\/[^/]+\/cancel$/.test(new URL(response.url()).pathname));
  await activeScan.getByRole("button",{name:"取消",exact:true}).click();
  expect((await cancelResponse).status()).toBe(200);
  await page.request.get(`${backendOrigin}/api/test/stage12/release`);
  await expect(activeScan.getByText(/本轮已由作者取消/)).toBeVisible();

  const secondProject=await data<{project:{id:string}}>(await page.request.post(`${backendOrigin}/api/projects`,{headers:{"Idempotency-Key":randomUUID()},data:{title:"迟到响应隔离项目"}}));
  let releaseOldRequest:()=>void=()=>{};
  let markOldRequest:()=>void=()=>{};
  const oldRequestSeen=new Promise<void>(resolve=>{markOldRequest=resolve;});
  const oldRequestGate=new Promise<void>(resolve=>{releaseOldRequest=resolve;});
  await page.route(`**/api/projects/${projectId}/foreshadows?**`,async route=>{markOldRequest();await oldRequestGate;try{await route.continue();}catch{}});
  await draftBody.fill(`${await draftBody.inputValue()} E2E_PROJECT_SWITCH_DELAY`);
  await page.getByRole("button",{name:"保存草稿",exact:true}).click();
  await oldRequestSeen;
  const switchNavigation=page.goto(`/projects/${secondProject.project.id}/workspace`);
  await page.waitForURL(new RegExp(`/projects/${secondProject.project.id}/workspace`));
  releaseOldRequest();
  await switchNavigation;
  const secondTools=page.getByRole("region",{name:"有界问答与伏笔管理"});
  await expect(secondTools.getByText(/作者伏笔 V0/)).toBeVisible();
  await secondTools.locator(":scope > summary").click();
  await expect(secondTools.getByText("潮汐表的本地修订",{exact:true})).toHaveCount(0);
  await expect(secondTools.getByText("根据当前 Story Memory，这个问题已有可核对的答案。",{exact:true})).toHaveCount(0);
  await page.unroute(`**/api/projects/${projectId}/foreshadows?**`);
  await page.goto(`/projects/${projectId}/workspace`);await expect(tools).toBeVisible();await tools.locator(":scope > summary").click();
  await expect(recordTool.getByText("潮汐表的本地修订",{exact:true})).toBeVisible();

  await page.setViewportSize({width:1366,height:900});
  const summary1366=await tools.locator(":scope > summary").evaluate(summary=>{const title=summary.querySelector("div")!.getBoundingClientRect(),counter=summary.querySelector("small")!.getBoundingClientRect();return {titleLeft:title.left,counterLeft:counter.left};});
  expect(summary1366.titleLeft).toBeLessThan(summary1366.counterLeft);
  await snap(page,"story-qa-foreshadow-01-desktop-1366.png");
  await page.setViewportSize({width:1920,height:1080});
  const summary1920=await tools.locator(":scope > summary").evaluate(summary=>{const title=summary.querySelector("div")!.getBoundingClientRect(),counter=summary.querySelector("small")!.getBoundingClientRect();return {titleLeft:title.left,counterLeft:counter.left};});
  expect(summary1920.titleLeft).toBeLessThan(summary1920.counterLeft);
  await snap(page,"story-qa-foreshadow-02-desktop-1920.png");
  await page.setViewportSize({width:390,height:844});await page.reload();await expect(tools).toBeVisible();await tools.locator(":scope > summary").click();
  await expect(recordTool.getByText("作者确认的潮汐表线索",{exact:true})).toBeVisible();
  await expect(qa.getByText("根据当前 Story Memory，这个问题已有可核对的答案。",{exact:true}).first()).toBeVisible();
  await expect(tools.locator("form")).toHaveCount(0);
  await expect(tools.getByRole("button",{name:/提交问题|扫描已写正文|新建作者记录|保存修改|编辑|归档|接受|拒绝|保存为作者记录|重试|取消/})).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await snap(page,"story-qa-foreshadow-03-mobile-390.png");
  const statsAfter=await (await page.request.get(`${backendOrigin}/api/test/stage12/stats`)).json() as {provider_http_calls:number};
  expect(statsAfter.provider_http_calls).toBe(statsBefore.provider_http_calls);expect(statsAfter.provider_http_calls).toBe(0);
  expect(expectedConflictCount).toBe(1);expect(consoleErrors).toEqual([]);expect(pageErrors).toEqual([]);expect(requestErrors).toEqual([]);
});
