import { expect, test } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { writeFile } from "node:fs/promises";

const backendOrigin = process.env.E2E_BACKEND_ORIGIN!;
const prefix = process.env.E2E_ACCOUNT_PREFIX!;

test("G02 source-rendered brief keeps tail and coordinate citations after refresh", async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 960 });
  const pageErrors: string[] = [];
  page.on("pageerror", error => pageErrors.push(error.message));
  const account = `${prefix}g02${Date.now()}${randomUUID().slice(0, 5)}`;
  await page.goto("/register");
  await page.getByLabel("账号", { exact: true }).fill(account);
  await page.getByLabel("显示名称").fill("G02 来源验收");
  await page.getByLabel("恢复邮箱").fill(`${account}@example.test`);
  await page.locator('input[name="password"]').fill(`safe-${randomUUID()}`);
  const registrationPromise = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/api/auth/register"));
  await page.getByRole("button", { name: "创建账号", exact: true }).click();
  const registration = await registrationPromise;
  expect(registration.ok(), await registration.text()).toBe(true);
  const tutorialProjectId = (await registration.json()).data.onboarding.tutorial.project_id as string;
  await expect(page.getByRole("heading", { name: "继续你的故事", exact: true })).toBeVisible();
  await page.goto(`/projects/${tutorialProjectId}/workspace`);
  const projectId = tutorialProjectId;
  await expect(page.locator(".workspace-grid")).toBeVisible();
  const tail = "最后把银钥匙交给陈澈并得知弟弟还活着";
  const body = "E2E_G02_CITATION 温岚潮表坐标。" + "林默沿着长廊向前走，".repeat(28) + `${tail}。`;
  await page.locator("#draft-body").fill(body);
  await page.getByRole("button", { name: "保存草稿", exact: true }).click();
  await expect(page.getByRole("status").getByText(/草稿已保存于/)).toBeVisible();
  const createdPromise = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith(`/api/projects/${projectId}/analyses`));
  await page.getByRole("button", { name: "生成章节简报", exact: true }).click();
  const createdResponse = await createdPromise;
  expect(createdResponse.status(), await createdResponse.text()).toBe(202);
  const created = (await createdResponse.json()).data as { run_id: string };
  const runUrl = `${backendOrigin}/api/projects/${projectId}/analyses/${created.run_id}`;
  const getRun = async () => (await (await page.request.get(runUrl)).json()).data as any;
  await expect.poll(async () => (await getRun()).status).toBe("completed");
  const run = await getRun();
  const tailItem = run.analysis.items.find((item: any) => item.text.includes(tail));
  expect(tailItem).toBeTruthy();
  expect(tailItem.sources.some((source: any) => source.source_type === "draft_claim" && source.excerpt.includes(tail))).toBe(true);
  expect(run.analysis.summary).toContain(tail);
  expect(run.analysis.summary_sources.some((source: any) => source.excerpt.includes(tail))).toBe(true);
  expect(run.analysis.items.some((item: any) => item.text.includes("看得懂潮表上的坐标") && item.sources.some((source: any) => source.source_type === "source_span" && source.excerpt.includes("看得懂潮表上的坐标")))).toBe(true);
  const brief = page.locator('.writing-analysis-result[aria-label="章节简报结果"]');
  await expect(brief).toBeVisible();
  await expect(brief).toContainText(tail);
  await brief.getByText(/查看来源/).first().click();
  await expect(brief.locator(".source-kind",{hasText:"当前草稿"}).first()).toBeVisible();
  await page.screenshot({ path: info.outputPath("g02-before-refresh.png"), fullPage: true, animations: "disabled" });
  await page.reload();
  await expect(brief).toBeVisible();
  await expect(brief).toContainText(tail);
  const refreshed = await getRun();
  expect(refreshed.analysis).toEqual(run.analysis);
  await page.screenshot({ path: info.outputPath("g02-after-refresh.png"), fullPage: true, animations: "disabled" });
  const stats = await (await page.request.get(`${backendOrigin}/api/test/stage12/stats`)).json();
  expect(stats.provider_http_calls).toBe(0);
  expect(pageErrors).toEqual([]);
  await writeFile(info.outputPath("g02-browser-evidence.json"), JSON.stringify({ projectId, body, run, refreshed, stats, pageErrors }, null, 2));
});
